package com.altimetrik.interview.enums;

public enum ActivityEventType {
    TAB_HIDDEN,
    COPY_FROM_EDITOR,
    PASTE_IN_EDITOR,
    EXTERNAL_DROP_BLOCKED,
    CAMERA_STREAM_LOST,
    MICROPHONE_DISABLED_MANUALLY,
    CAMERA_DISABLED_MANUALLY,
    NO_FACE_DETECTED,
    MULTIPLE_FACES_DETECTED
}
